insert into EXCHANGE_VALUE("ID", "FROM_CURRENCY", "TO_CURRENCY", "CONVERSION_MULTIPLE") values(1001, 'USD', 'INR', 65);
insert into EXCHANGE_VALUE("ID", "FROM_CURRENCY", "TO_CURRENCY", "CONVERSION_MULTIPLE") values(1002, 'USD', 'EUR', 75);
insert into EXCHANGE_VALUE("ID", "FROM_CURRENCY", "TO_CURRENCY", "CONVERSION_MULTIPLE") values(1003, 'AUD', 'INR', 50);